# Generated by Django 4.0.3 on 2022-05-18 09:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='embed',
        ),
        migrations.RemoveField(
            model_name='videos',
            name='ass',
        ),
        migrations.AddField(
            model_name='videos',
            name='viewers',
            field=models.ManyToManyField(blank=True, related_name='viewers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='videos',
            name='description',
            field=models.TextField(default='Nothing yet', max_length=300, null=True),
        ),
        migrations.DeleteModel(
            name='Video_View',
        ),
    ]
